apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2024-12-19T10:40:54Z"
  generation: 1
  name: app.bapatlas.site
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  certManager:
    enabled: true
  channel: stable
  cloudProvider: aws
  configBase: s3://app.kops.bapatlas.site/app.bapatlas.site
  dnsZone: bapatlas.site
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: control-plane-ap-south-1a
      name: a
    manager:
      backupRetentionDays: 90
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: control-plane-ap-south-1a
      name: a
    manager:
      backupRetentionDays: 90
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  - ::/0
  kubernetesVersion: 1.30.7
  masterPublicName: api.app.bapatlas.site
  metricsServer:
    enabled: true
  networkCIDR: 172.20.0.0/16
  networking:
    calico: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  - ::/0
  subnets:
  - cidr: 172.20.0.0/17
    name: ap-south-1a
    type: Public
    zone: ap-south-1a
  - cidr: 172.20.128.0/17
    name: ap-south-1b
    type: Public
    zone: ap-south-1b
  topology:
    dns:
      type: Public
