apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    project: instana
    tier: mysql-db
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPassword | b64enc | quote }}