apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    project: instana
    tier: mysql-db
spec:
  clusterIP: None
  selector:
    app: mysql
  ports:
    - port: {{ .Values.service.port }}
      name: mysql