apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  labels:
    project: instana
    tier: db
spec:
  serviceName: "mongo"
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: siva9666/mongo-instana:monitoring-v1
          ports:
            - containerPort: 27017
              name: mongo
          resources:
            requests:
              memory: 1Gi
              cpu: 250m
            limits:
              memory: 2Gi
              cpu: 500m
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "echo 'db.stats().ok' | mongo localhost:27017/test --quiet"
            initialDelaySeconds: 40
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 5

          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "echo 'db.stats().ok' | mongo localhost:27017/test --quiet"
            initialDelaySeconds: 40
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 5

          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-storage
  volumeClaimTemplates:
    - metadata:
        name: mongo-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
        storageClassName: instana
