apiVersion: v1 
kind: Service 
metadata:
  name: catalogue 
  labels:
    project: instana 
    tier: catalogue 
spec:
  selector:
    app: catalogue 
  ports:
    - port: {{ .Values.service.port }} 
      targetPort: {{ .Values.service.port }} 