apiVersion: v1
kind: Service
metadata:
  name: rabbit
  labels:
    project: instana
    tier: queue
spec:
  clusterIP: None
  selector:
    app: rabbit
  ports:
    - port: 5672
      name: rabbitmq
