apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbit
  labels:
    project: instana
    tier: queue
spec:
  serviceName: "rabbit"
  replicas: 1
  selector:
    matchLabels:
      app: rabbit
  template:
    metadata:
      labels:
        app: rabbit
    spec:
      containers:
        - name: rabbit
          image: siva9666/rabbit-instana:v1
          ports:
            - containerPort: 5672
              name: rabbitmq
          volumeMounts:
            - name: rabbit-storage
              mountPath: /var/lib/rabbitmq
  volumeClaimTemplates:
    - metadata:
        name: rabbit-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
        storageClassName: instana
