apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
    project: expense
spec:
  type: NodePort
  selector:
    app: frontend
    project: expense
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32121
      protocol: TCP
