apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  labels:
    app: frontend
    project: expense
spec:
  type: LoadBalancer
  selector:
    app: frontend
    project: expense
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
