apiVersion: v1
kind: Pod
metadata:
  name: pod-with-init-container
spec:
  containers:
    - name: app-container
      image: nginx:1.25.2
      ports:
        - containerPort: 80
  initContainers:
    - name: init-container
      image: busybox:1.35
      command: ["sh", "-c", "echo Initializing...; sleep 5;"]
