apiVersion: v1
kind: Service
metadata:
  name: expense
  labels:
    app: frontend
    project: expense
spec:
  type: {{ .Values.service.type }}
  selector:
    app: frontend
    project: expense
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
