apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  labels:
    project: instana
    tier: cache-db
spec:
  ports:
  - port: 6379
    name: redis
  clusterIP: None
  selector:
    app: redis
