apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  labels:
    project: instana
    tier: cache
spec:
  serviceName: "redis-headless"
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        project: instana
        tier: cache
    spec:
      containers:
      - name: redis
        image: siva9666/redis-instana:v1
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - name: redis-data
          mountPath: /data
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "512Mi"
            cpu: "100m"
          limits:
            memory: "1024Mi"
            cpu: "200m"
  volumeClaimTemplates:
  - metadata:
      name: redis-data
      labels:
        project: instana
        tier: cache
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: instana
      resources:
        requests:
          storage: 1Gi
