apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    project: instana
    tier: web
spec:
  replicas: 3
  selector:
    matchLabels:
      project: instana
      tier: web
  template:
    metadata:
      labels:
        project: instana
        tier: web
    spec:
      containers:
      - name: web
        image: siva9666/web-instana:v2
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /health
            port: 80
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: web-config
