apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::427366301535:role/green-eks-node-group-20241108090421762500000002
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: "- userarn: arn:aws:iam::427366301535:user/instana\n  username: instana\n
    \ \n- userarn: arn:aws:iam::427366301535:user/expense\n  username: expense\n"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- groups:\n  - system:bootstrappers\n  - system:nodes\n  rolearn: arn:aws:iam::427366301535:role/green-eks-node-group-20241108090421762500000002\n  username: system:node:{{EC2PrivateDNSName}}\n","mapUsers":"- userarn: arn:aws:iam::427366301535:user/instana\n  username: instana\n  \n- userarn: arn:aws:iam::427366301535:user/expense\n  username: expense\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2024-11-08T09:14:44Z","name":"aws-auth","namespace":"kube-system","resourceVersion":"1832","uid":"14872923-b0e5-4f87-b374-19f803989dbe"}}
  name: aws-auth
  namespace: kube-system
  resourceVersion: "20138"
  uid: 14872923-b0e5-4f87-b374-19f803989dbe