---
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
data:
  token: aHZzLmMwUjkxamtSbVpJcGNnWWVpWnUzR2lNQg==
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://ws.bapatlas.site:8200/"
      path: "kv"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-example
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: test
  data:
  - secretKey: NAME
    remoteRef:
      key: test
      property: NAME