replicaCount: 1

image:
  repository: siva9666/expense-frontend
  tag: v1
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort: 32121

resources:
  requests:
    memory: 500Mi
    cpu: 100m
  limits:
    memory: 600Mi
    cpu: 200m

hpa:
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

config:
  nginxConf: |
    events {}

    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';
        access_log /var/log/nginx/access.log main;
        error_log /var/log/nginx/error.log;

        server {
            listen 80 default_server;
            server_name localhost;

            root /usr/share/nginx/html;
            index index.html;

            location / {
                try_files $uri $uri/ =404;
            }

            location /api/ {
                proxy_pass http://backend-svc:8080/;
                proxy_http_version 1.1;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }

            location /health {
                stub_status on;
                access_log off;
            }
        }
    }
