---
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: kube-system
data:
  token: aHZzLmMwUjkxamtSbVpJcGNnWWVpWnUzR2lNQg==
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://ws.bapatlas.site:8200/"
      path: "kv"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"
          namespace: kube-system
