---
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
  labels:
    project: instana
    tier: web
data:
  nginx.conf: |
    events {}

    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        # Log format
        log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

        access_log /var/log/nginx/access.log main;
        error_log /var/log/nginx/error.log;

        # Default server configuration
        server {
            listen 80 default_server;
            server_name localhost;

            root /usr/share/nginx/html;
            index index.html;

            location / {
                try_files $uri $uri/ =404;
            }

            location /api/catalogue/ {
                proxy_pass http://catalogue:8080/;
                proxy_http_version 1.1;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
            location /api/user/ {
                proxy_pass http://user:8080/;
                proxy_http_version 1.1;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
            location /api/cart/ {
                proxy_pass http://cart:8080/;
                proxy_http_version 1.1;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
            location /api/shipping/ {
                proxy_pass http://shipping:8080/;
                proxy_http_version 1.1;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
            location /api/payment/ {
                proxy_pass http://payment:8080/;
                proxy_http_version 1.1;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }

            location /health {
                stub_status on;
                access_log off;
            }

            # Additional location blocks or configurations can go here
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    project: instana
    tier: web
spec:
  replicas: 2
  selector:
    matchLabels:
      project: instana
      tier: web
  template:
    metadata:
      labels:
        project: instana
        tier: web
    spec:
      containers:
      - name: web
        image: siva9666/web-instana:monitoring-v2
        ports:
        - containerPort: 80
        resources:
            requests:
              memory: 128Mi
              cpu: 30m
            limits:
              memory: 256Mi
              cpu: 60m
        readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5      
            periodSeconds: 10           
            timeoutSeconds: 2           
            successThreshold: 1
            failureThreshold: 3          
        livenessProbe:
            httpGet:
              path: /             
              port: 80
            initialDelaySeconds: 10    
            periodSeconds: 10          
            timeoutSeconds: 2            
            successThreshold: 1      
            failureThreshold: 3
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: web-config
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: web-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web
  minReplicas: 2
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    project: instana
    tier: web
spec:
  type: NodePort
  selector:
    project: instana
    tier: web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32122