apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping-config
  labels:
    project: instana
    tier: shipping-backend
data:
  DB_HOST: {{ .Values.config.DB_HOST | quote }}
  DB_PORT: {{ .Values.config.DB_PORT | quote }}
  CART_ENDPOINT: {{ .Values.config.CART_ENDPOINT | quote }}