apiVersion: v1
kind: Secret
metadata:
  name: shipping-secrets
  labels:
    project: instana
    tier: shipping-backend
type: Opaque
data:
  DB_USER : {{ .Values.secrets.DB_USER | quote }}  
  DB_PASSWD : {{ .Values.secrets.DB_PASSWD | quote }}  