apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
    project: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      project: expense
  template:
    metadata:
      labels:
        app: backend
        project: expense
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secrets
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: {{ .Values.backend.resources.requests.memory }}
              cpu: {{ .Values.backend.resources.requests.cpu }}
            limits:
              memory: {{ .Values.backend.resources.limits.memory }}
              cpu: {{ .Values.backend.resources.limits.cpu }}
