apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  labels:
    app: backend
    project: expense
type: Opaque
data:
  DB_USER: {{ .Values.backend.secrets.DB_USER | quote }}
  DB_PWD: {{ .Values.backend.secrets.DB_PWD | quote }}
 