apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dispatch.fullname" . }}-config
  labels:
    {{- include "dispatch.labels" . | nindent 4 }}
data:
  AMQP_HOST: {{ .Values.env.AMQP_HOST | quote }}