apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dispatch.fullname" . }}-secrets
  labels:
    {{- include "dispatch.labels" . | nindent 4 }}
type: Opaque
data:
  AMQP_USER: {{ .Values.env.AMQP_USER }}
  AMQP_PASS: {{ .Values.env.AMQP_PASS }}
