apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.env }}-{{ .Values.name }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
  selector:
      {{- toYaml .Values.labels | nindent 6 }}
    