apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    type: db
    project: expense
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: siva9666/expense-mysql:v1
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-persistent-storage
      labels:
        app: mysql
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: expense
      resources:
        requests:
          storage: 1Gi
