apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    type: db
    project: expense
spec:
  clusterIP: None
  selector:
    app: mysql
  ports:
    - port: 3306
      name: mysql


# kubectl run debug --image=siva9666/debug-utility:v1 --restart=Never -- sleep 3600