replicaCount: 1

image:
  repository: siva9666/rabbit-instana
  tag: v1

service:
  type: ClusterIP
  port: 5672

resources:
  requests:
    memory: "1Gi"
    cpu: "800m"
  limits:
    memory: "2Gi"
    cpu: "1000m"

storage:
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  storageClassName: instana

probes:
  liveness:
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

  readiness:
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3