apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  labels:
    project: instana
    tier: shipping
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shipping
  template:
    metadata:
      labels:
        app: shipping
    spec:
      containers:
        - name: shipping
          image: siva9666/shipping-instana:v1
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "1Gi"
              cpu: 800m
            limits:
              memory: "2Gi"
              cpu: 1000m
          envFrom:
            - configMapRef:
                name: shipping-config
            - secretRef:
                name: shipping-secrets
