apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: expense
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
allowVolumeExpansion: true
parameters:
  csi.storage.k8s.io/fstype: xfs
  type: gp3
  encrypted: "true"
