apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  labels:
    project: instana
    tier: catalogue-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalogue
      tier: backend
  template:
    metadata:
      labels:
        app: catalogue
    spec:
      containers:
        - name: catalogue
          image: siva9666/catalogue-instana:monitoring-v1
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 200m
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10      
            periodSeconds: 10           
            timeoutSeconds: 2           
            successThreshold: 1
            failureThreshold: 3          
          livenessProbe:
            httpGet:
              path: /health             
              port: 8080
            initialDelaySeconds: 10    
            periodSeconds: 10            
            timeoutSeconds: 2            
            successThreshold: 1      
            failureThreshold: 3 
          envFrom:
            - configMapRef:
                name: catalogue-config
