apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  labels:
    project: instana
    tier: catalogue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: catalogue
  template:
    metadata:
      labels:
        app: catalogue
    spec:
      containers:
        - name: catalogue
          image: siva9666/catalogue-instana:v1
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: catalogue-config
