apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-config
  labels:
    project: instana
    tier: backend-cart
data:
  CATALOGUE_HOST: "catalogue"
  CATALOGUE_PORT: "8080"
  REDIS_HOST: "redis-headless"
