apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  labels:
    project: instana
    tier: backend-cart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart
      tier: backend
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
        - name: cart
          image: siva9666/cart-instana:monitoring-v1
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 100Mi
              cpu: 50m
            limits:
              memory: 200Mi
              cpu: 100m
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5      
            periodSeconds: 10           
            timeoutSeconds: 2           
            successThreshold: 1
            failureThreshold: 3          
          livenessProbe:
            httpGet:
              path: /health             
              port: 8080
            initialDelaySeconds: 10    
            periodSeconds: 10            
            timeoutSeconds: 2            
            successThreshold: 1      
            failureThreshold: 3 
          envFrom:
            - configMapRef:
                name: cart-config
