apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  labels:
    project: instana
    tier: user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
        - name: cart
          image: siva9666/cart-instana:v1
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 100Mi
              cpu: 50m
            limits:
              memory: 200Mi
              cpu: 100m
          envFrom:
            - configMapRef:
                name: cart-config
