apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  labels:
    project: instana
    tier: user
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
        - name: cart
          image: siva9666/cart-instana:v1
          ports:
            - containerPort: 8080
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8080
          #   initialDelaySeconds: 60
          #   periodSeconds: 10
          #   timeoutSeconds: 5
          #   failureThreshold: 3
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8080
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          #   timeoutSeconds: 5
          #   failureThreshold: 3
          # resources:
          #   requests:
          #     cpu: "10m"
          #     memory: "128Mi"
          #   limits:
          #     cpu: "25m"
          #     memory: "256Mi"
          envFrom:
            - configMapRef:
                name: cart-config
