apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatch
  labels:
    project: instana
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      project: instana
      tier: backend
  template:
    metadata:
      labels:
        project: instana
        tier: backend
    spec:
      containers:
      - name: dispatch
        image: siva9666/dispatch-instana:v1
        ports:
        - containerPort: 8080
        resources:
            requests:
              memory: 128Mi
              cpu: 50m
            limits:
              memory: 256Mi
              cpu: 100m
        readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5      
            periodSeconds: 10           
            timeoutSeconds: 2           
            successThreshold: 1
            failureThreshold: 3          
        livenessProbe:
            httpGet:
              path: /health             
              port: 8080
            initialDelaySeconds: 10    
            periodSeconds: 10          
            timeoutSeconds: 2            
            successThreshold: 1      
            failureThreshold: 3 
        envFrom:
        - configMapRef:
            name: dispatch-config
        - secretRef:
            name: dispatch-secrets
