apiVersion: v1
kind: Service
metadata:
  name: dispatch
  labels:
    project: instana
    tier: dispatch
spec:
  selector:
    project: instana
    tier: dispatch
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
