apiVersion: v1 
kind : Service 
metadata :
   name : shipping 
   labels :
     project : instana 
     tier : shipping-backend 
spec :
   selector :
     app : shipping  
   ports :
     - port : {{ .Values.service.port }}  
       targetPort : {{ .Values.service.port }}