apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    project: instana
    tier: web
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    project: instana
    tier: web
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
