apiVersion: v1 
kind : Service 
metadata :
   name : web 
   labels :
     project : instana 
     tier : web 
spec :
   type : {{ .Values.service.type }}  
   selector :
     project : instana  
     tier : web  
   ports :
     - protocol : TCP  
       port : {{ .Values.service.port }}  
       targetPort : {{ .Values.service.port }}  
       nodePort : {{ .Values.service.nodePort }}