apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-config
  labels:
    project: instana
    tier: payment
data:
  CART_HOST: "cart"
  CART_PORT: "8080"
  USER_HOST: "user"
  USER_PORT: "8080"
  AMQP_HOST: "rabbit"
