apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    project: instana
    tier: payment
spec:
  replicas: 2
  selector:
    matchLabels:
      project: instana
      tier: payment
  template:
    metadata:
      labels:
        project: instana
        tier: payment
    spec:
      containers:
      - name: payment
        image: siva9666/payment-instana:v1
        ports:
        - containerPort: 8080
        resources:
            requests:
              memory: 500Mi
              cpu: 200m
            limits:
              memory: 700Mi
              cpu: 400m
        envFrom:
        - configMapRef:
            name: payment-config
        - secretRef:
            name: payment-secrets
