apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    project: instana
    tier: payment-backend
spec:
  selector:
    project: instana
    tier: payment
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
