apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  labels:
    app: backend
    project: expense
data:
  DB_HOST: {{ .Values.backend.config.DB_HOST }}
  DB_DATABASE: {{ .Values.backend.config.DB_DATABASE }}
