apiVersion: v2
name: stateful-apps
description: A Helm chart for deploying MongoDB, MySQL, Redis, and RabbitMQ
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: Konka
    email: konka@example.com