apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    project: instana
    tier: mysql-db
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: Um9ib1Nob3A8MXI8QGJhc2VfbWV0YQ==  # Base64 encoded password: RoboShop@1
