apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.env }}-{{ .Values.name }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
data:
  {{- range $key, $value := .Values.configmap }}
  {{ $key }}: {{- if contains "\n" (toString $value) }} |
    {{- $value | nindent 4 }}
  {{- else }} {{ $value | quote }}
  {{- end }}
  {{- end }}

