replicaCount: 2

image:
  repository: siva9666/cart-instana
  tag: monitoring-v1

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    memory: "100Mi"
    cpu: "50m"
  limits:
    memory: "200Mi"
    cpu: "100m"

probes:
  liveness:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 2
    successThreshold: 1
    failureThreshold: 3

  readiness:
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 2
    successThreshold: 1
    failureThreshold: 3

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 3
  cpuUtilizationTarget: 50

config:
  CATALOGUE_HOST: "catalogue"
  CATALOGUE_PORT: "8080"
  REDIS_HOST: "redis-headless"