apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.env }}-{{ .Values.name }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
spec:
  selector:
    {{- toYaml .Values.labels | nindent 4 }}
  ports:
    - name: {{ .Values.env }}-{{ .Values.name }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  clusterIP: None