apiVersion: v1
kind: Service
metadata:
  name: redis 
  labels:
    project: instana 
    tier: cache-db 
spec:
  ports:
    - port: {{ .Values.service.port }}
      name: redis 
  clusterIP: None
  selector:
    app: {{ .Release.Name }} 