apiVersion: v1
kind: Service
metadata:
  name: redis-headless 
  labels:
    project: instana 
    tier: cache-db 
spec:
  ports:
    - port: {{ .Values.service.port }}
      name: redis 
  clusterIP: None # Headless service for StatefulSet.
  selector:
    app: {{ .Release.Name }} 