apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
  labels:
    project: instana
spec:
  serviceName: "redis"
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      tier: cache-db
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        project: instana
        tier: cache-db
    spec:
      containers:
      - name: redis
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.service.port }}
          name: redis

        volumeMounts:
        - name: redis-data
          mountPath: /data

        resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}

        livenessProbe:
          exec:
            command:
              - redis-cli
              - -p
              - "6379" 
              - ping
          initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
          timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
          failureThreshold: {{ .Values.probes.liveness.failureThreshold }}

        readinessProbe:
          exec:
            command:
              - redis-cli
              - -p
              - "6379"  
              - ping
          initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.probes.readiness.periodsSeconds }}
          timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
          failureThreshold: {{ .Values.probes.readiness.failureThreshold }}

      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data

  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: {{ .Values.storage.accessModes | toJson }}
        resources:
          requests:
            storage: {{ .Values.storage.size }}
        storageClassName: {{ .Values.storage.storageClassName }}