env: dev
name: cart
labels:
  app: cart
  tier: application
replicaCount: 2
image:
  repository: siva9666
  name: cart-instana
  tag: monitoring-v1
resources:
  requests:
    memory: "128Mi"
    cpu: "50m"
  limits:
    memory: "256Mi"
    cpu: "75m"
health_check:
  path: /health
probes:
  enabled: true
  liveness:
    initialDelaySeconds: 10    
    periodSeconds: 10            
    timeoutSeconds: 2            
    successThreshold: 1      
    failureThreshold: 3 
  readiness:
    initialDelaySeconds: 10      
    periodSeconds: 10           
    timeoutSeconds: 2           
    successThreshold: 1
    failureThreshold: 3 

configmap:
  CATALOGUE_HOST: "dev-catalogue"
  CATALOGUE_PORT: "8080"
  REDIS_HOST: "dev-redis"
hpa:
  minReplicas: 2
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
service:
  port: 8080

secrets:
  enabled: false


