apiVersion: v1 
kind: Service 
metadata:
  name: user 
  labels:
    project: instana 
    tier: user-backend 
spec:
  selector:
    tier: user-backend 
  ports:
    - port: {{ .Values.service.port }} 
      targetPort: {{ .Values.service.port }} 