apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    project: instana
    tier: mongo-db
spec:
  clusterIP: None
  selector:
    app: mongo
  ports:
    - port: {{ .Values.service.port }}
      name: mongo