apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    project: instana
    tier: mongo-db
spec:
  clusterIP: None # Headless service for StatefulSet.
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      name: mongo