replicaCount: 1

image:
  repository: siva9666/mysql-instana
  tag: v1

service:
  type: ClusterIP
  port: 3306

mysql:
  rootPassword: Um9ib1Nob3BAMQ==
resources:
  requests:
    memory: "1Gi"
    cpu: "250m"
  limits:
    memory: "2Gi"
    cpu: "500m"

storage:
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  storageClassName: instana