replicaCount: 1

image:
  repository: siva9666/mongo-instana
  tag: monitoring-v1

service:
  port: 27017

resources:
  requests:
    memory: "1Gi"
    cpu: "500m"
  limits:
    memory: "2Gi"
    cpu: "700m"

storage:
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  storageClassName: instana