apiVersion: v1 
kind: Service 
metadata:
  name: cart 
  labels:
    project: instana 
    tier: backend-cart 
spec:
  selector:
    app: cart 
  ports:
    - port: {{ .Values.service.port }} 
      targetPort: {{ .Values.service.port }} 