apiVersion: v1 
kind : Service 
metadata :
   name : payment 
   labels :
     project : instana 
     tier : payment-backend 
spec :
   selector :
     project : instana 
     tier : payment-backend  
   ports :
     - protocol : TCP  
       port : {{ .Values.service.port }}  
       targetPort : {{ .Values.service.port }}