apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    type: db
    project: expense
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.secret.rootPassword | b64enc | quote }}
