apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  labels:
    app: backend
    project: expense
spec:
  selector:
    app: backend
    project: expense
  ports:
    - port: 8080
      targetPort: 8080
      name: http
