apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    project: instana
    tier: queue-db
spec:
  clusterIP: None
  selector:
    app: {{ .Release.Name }}
    tier: queue-db 
  ports:
    - port: {{ .Values.service.port }}
      name: rabbitmq