replicaCount: 2

image:
  repository: siva9666/shipping-instana
  tag: monitoring-v1

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    memory: "1Gi"
    cpu: "800m"
  limits:
    memory: "2Gi"
    cpu: "1000m"

probes:
  liveness:
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 2
    successThreshold: 1
    failureThreshold: 3

  readiness:
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 2
    successThreshold: 1
    failureThreshold: 3

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 3
  cpuUtilizationTarget: 80

config:
  DB_HOST: "mysql"
  DB_PORT: "3306"
  CART_ENDPOINT: "cart:8080"

secrets:
  DB_USER: c2hpcHBpbmc=
  DB_PASSWD: Um9ib1Nob3BAMQ==